package main

import (
	"context"
	"log"
	"os"
	"os/signal"
	"syscall"
	"time"

	_ "workshop-be/internal/docs" // swagger docs generated by swag

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"github.com/gofiber/swagger"
	_ "github.com/gofiber/swagger" // swagger handler

	"github.com/joho/godotenv"

	"workshop-be/internal/auth"
	"workshop-be/internal/db"
	"workshop-be/internal/middleware"
)

// @title Workshop BE API
// @version 1.0
// @description API for authentication workshop
// @BasePath /
// @schemes http
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
func main() {
	_ = godotenv.Load() // load .env if present

	app := fiber.New()
	app.Use(logger.New())

	// Health
	app.Get("/healthz", func(c *fiber.Ctx) error { return c.SendStatus(fiber.StatusOK) })

	// Root
	app.Get("/", func(c *fiber.Ctx) error { return c.JSON(fiber.Map{"message": "hello world"}) })

	// Env & DB init
	dbPath := os.Getenv("DB_PATH")
	jwtSecret := os.Getenv("JWT_SECRET")
	if jwtSecret == "" {
		log.Println("warning: JWT_SECRET not set, using insecure default (dev only)")
		os.Setenv("JWT_SECRET", "insecure-dev-secret-change-me")
	}
	// init database
	db.Init(dbPath, &auth.User{})

	// Auth routes
	authSvc := auth.NewService()
	authGroup := app.Group("/api/v1/auth")
	auth.RegisterRoutes(authGroup, authSvc)
	authHandler := auth.NewHandler(authSvc)
	// Protected route (me)
	authGroup.Get("/me", middleware.AuthRequired(), authHandler.Me)

	// Profile routes (protected)
	profileGroup := app.Group("/api/v1/profile", middleware.AuthRequired())
	profileHandler := auth.NewHandler(authSvc)
	profileGroup.Get("/", profileHandler.GetProfile)
	profileGroup.Put("/", profileHandler.UpdateProfile)

	// Swagger endpoint
	app.Get("/swagger/*", swagger.HandlerDefault)

	port := os.Getenv("PORT")
	if port == "" {
		port = "3000"
	}

	go func() {
		if err := app.Listen(":" + port); err != nil {
			log.Printf("shutting down server: %v\n", err)
		}
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	log.Println("Gracefully shutting down...")
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if err := app.Shutdown(); err != nil {
		log.Printf("error on shutdown: %v", err)
	}
	if err := db.Close(); err != nil {
		log.Printf("error closing db: %v", err)
	}
	_ = ctx
	log.Println("Server stopped")
}
